server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
  sql:
    init:
      mode: always

  #---
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${EWM_DATASOURCE_URL}
    username: ${EWM_DB_USER}
    password: ${EWM_DB_PASSWORD}

logging:
  level:
    ru:
      practicum:
        ewm: debug