server:
  port: 9090

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
  sql:
    init:
      mode: always

  datasource:
    driverClassName: org.postgresql.Driver
    url: ${STAT_DATASOURCE_URL}
    username: ${STAT_DB_USER}
    password: ${STAT_DB_PASSWORD}

---

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ewm
    username: test
    password: test
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true

logging:
  level:
    ru:
      practicum:
        stat: debug