CREATE TABLE IF NOT EXISTS applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app_name VARCHAR(100),
    CONSTRAINT pk_app PRIMARY KEY (id),
    CONSTRAINT UQ_APP_NAME UNIQUE (app_name)
);

CREATE TABLE IF NOT EXISTS statistics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app_id BIGINT,
    uri VARCHAR(100),
    ip VARCHAR(15),
    add_time timestamp,
    CONSTRAINT pk_statistics PRIMARY KEY (id),
    CONSTRAINT fk_statistic_to_app FOREIGN KEY(app_id) REFERENCES applications(id)
);